name: mekanly
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  bloc_concurrency: ^0.2.5
  common:
    path: module/common
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  extended_nested_scroll_view: ^6.2.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  gen:
    path: module/gen
  get_it: ^8.0.2
  image_picker: ^1.1.2
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  pinput: ^5.0.1
  pull_to_refresh: ^2.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  stream_transform: ^2.1.0
  # mekanly_video_player:
  #   git:
  visibility_detector: ^0.4.0+2
  video_player: ^2.9.5
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  flutter_gen: ^5.10.0
  gallery_saver_plus: ^3.2.8
  flutter_inappwebview: ^6.1.5
  intl: ^0.20.2
  collection: ^1.18.0
  extended_image: ^8.2.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_logo_app_new.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
